server:
  port: 8080
  #测试阶段先不使用
  #servlet:
  #  context-path: /checky

Spring:
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    url: jdbc:log4jdbc:mysql://120.78.150.152:3306/checky?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: checky
    password: asdfgh
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.DriverSpy
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15


mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.whu.checky.domain


#logging:
#  level:
#    com.whu.checky.mapper: debug

spring:
    redis:
        database: 0      # Redis数据库索引（默认为0）
        host: 120.78.150.152  # Redis服务器地址
        port: 6379       # Redis服务器连接端口
        password: asdfghjkl        # Redis服务器连接密码（默认为空）
        timeout: 0       # 连接超时时间（毫秒）
        lettuce:
            pool:
                max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
                max-idle: 8    # 连接池中的最大空闲连接
                max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
                min-idle: 0    # 连接池中的最小空闲连接
